# Configuration Fly.io pour Nuxt Frontend
app = "your-app-frontend"
primary_region = "cdg"

[build]
  dockerfile = "apps/frontend/Dockerfile"

[env]
  NODE_ENV = "production"
  NUXT_HOST = "0.0.0.0"
  NUXT_PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  release_command = "npm run build" 